### ISSUE TITLE
Wiki link suggestions are not displayed

### ISSUE THREAD

**Issue by nmboris** [davidjroos/obsidian-notswift#4]
In the CSS there is a selector

```css
.suggestion-container {
	display: none;
}
```

that hides the suggestion container :) - which is not good if you want to see the suggestions for wiki links
