### ISSUE TITLE
Double box-shadow on focus

### ISSUE THREAD

**Issue by nmboris** [davidjroos/obsidian-notswift#5]
When selecting folder list entries, there are double box shadows around the individual entries.

I was able to temporarily cure this in an amateur way by making the following CSS change:

```css
body:not(.is-phone) .workspace-leaf.mod-active .tree-item-self.has-focus {
	box-shadow: none;
}
```
<img width="397" alt="SCR-20231013-ofyn" src="https://github.com/davidjroos/obsidian-notswift/assets/63914278/06a7166a-7428-4982-ba8f-2c95d6829794">
